# Generated by Django 3.1 on 2021-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayupload',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
    ]
