# Generated by Django 3.2.3 on 2021-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210115_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='phoneNo',
            field=models.CharField(max_length=12),
        ),
    ]
