# Generated by Django 3.2.3 on 2021-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_patientregistration_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='discription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
